
### OBTENER TODOS LOS USUARIOS
GET http://localhost:8080/api/user
Content-Type: application/json


### CREAR USUARIO -- ROL ADMIN
POST http://localhost:8080/api/authentication/register/admin
Content-Type: application/json

{
  "name": "administrador desde api",
  "username": "admin-api",
  "password": "password",
  "message": "Soy un administrador creado desde la API",

}

### LOGIN - OBTENER TOKEN
POST http://localhost:8080/api/authentication/login
Content-Type: application/json

{
  "username": "juanito",
  "password": "password"
}

### OBTENER TODOS LOS USUARIOS CON ROL CLIENT (SOLO ADMIN)
GET http://localhost:8080/api/client
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyODI4OSwiZXhwIjoxNzUzMTE0Njg5fQ.OyJsuoSM28v4eS8tfhqi1EG92c3y2wltEc6R-I4vkA_C1LSMqk4aRKtxd6NjOfNONdleVUusmlBk0k0OpgApOQ


### OBTENER TODOS LOS USUARIOS INDEPENDIENTE DEL ROL (SOLO ADMIN)
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyODI4OSwiZXhwIjoxNzUzMTE0Njg5fQ.OyJsuoSM28v4eS8tfhqi1EG92c3y2wltEc6R-I4vkA_C1LSMqk4aRKtxd6NjOfNONdleVUusmlBk0k0OpgApOQ


### OBTENER TODOS LOS USUARIOS CON ROL DEVELOPER (SOLO DEVELOPER)
GET http://localhost:8080/api/developer
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyODI4OSwiZXhwIjoxNzUzMTE0Njg5fQ.OyJsuoSM28v4eS8tfhqi1EG92c3y2wltEc6R-I4vkA_C1LSMqk4aRKtxd6NjOfNONdleVUusmlBk0k0OpgApOQ

### OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/product
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyODI4OSwiZXhwIjoxNzUzMTE0Njg5fQ.OyJsuoSM28v4eS8tfhqi1EG92c3y2wltEc6R-I4vkA_C1LSMqk4aRKtxd6NjOfNONdleVUusmlBk0k0OpgApOQ


### OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyMjkzMiwiZXhwIjoxNzUzMTA5MzMyfQ.ei-YIY-iWqmnLop7fzLYFBhM20Mg43HyxwCbjnnZGF0M_CLb9kPvbcsthFsMtIaJ_0egANPaVHv3R4Mm4cw4rg


### CREAR UN NUEVO PRODUCTO
POST http://localhost:8080/api/product
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyMjkzMiwiZXhwIjoxNzUzMTA5MzMyfQ.ei-YIY-iWqmnLop7fzLYFBhM20Mg43HyxwCbjnnZGF0M_CLb9kPvbcsthFsMtIaJ_0egANPaVHv3R4Mm4cw4rg

{
  "name": "producto4",
  "sku": "sku4",
  "price": 1990.0,
  "description": "descripcion del producto numero 4",
  "stock": 10
}

### OBTENER TODOS LOS PRODUCTOS (Muestra el nuevo producto)
GET http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqdWFuaXRvIiwiaWF0IjoxNzUzMDI4NTcyLCJleHAiOjE3NTMxMTQ5NzJ9.wOle_Kuud87-DTIk8-ujoPgBrhw1Q-bq6OqjlpGdpqAiVPgZO9jIp4DJpff692fWzktxrVrpa4DhXNnodOpZDA


### CREAR COMPRA (ERROR STOCK INSUFICIENTE)
POST http://localhost:8080/api/cart
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqdWFuaXRvIiwiaWF0IjoxNzUzMDI4NTcyLCJleHAiOjE3NTMxMTQ5NzJ9.wOle_Kuud87-DTIk8-ujoPgBrhw1Q-bq6OqjlpGdpqAiVPgZO9jIp4DJpff692fWzktxrVrpa4DhXNnodOpZDA

{
  "clientId": 2,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### CREAR COMPRA (PRODUCTOS DISPONIBLES)
POST http://localhost:8080/api/cart
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqdWFuaXRvIiwiaWF0IjoxNzUzMDI4NTcyLCJleHAiOjE3NTMxMTQ5NzJ9.wOle_Kuud87-DTIk8-ujoPgBrhw1Q-bq6OqjlpGdpqAiVPgZO9jIp4DJpff692fWzktxrVrpa4DhXNnodOpZDA

{
  "clientId": 2,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 3,
      "quantity": 1
    }
  ]
}

### OBTENER EL DETALLE DE UNA COMPRA
GET http://localhost:8080/api/cart/orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc1MzAyODA5NywiZXhwIjoxNzUzMTE0NDk3fQ.-YfyQB-KNoeVcv1sjxpKLi6Y40Bn8Lcr_NFOILcwdYJUHbikFD2u2eHmaryE1gUMe-qn0hT2a8H1n5BSKIyDQw






