### OBTENER TODOS LOS CLIENTES
GET http://localhost:8080/api/client
Content-Type: application/json


### CREAR UN NUEVO CLIENTE -- TIENE ROL COMPRA
POST http://localhost:8080/api/client
Content-Type: application/json

{
  "name": "juan",
  "username": "juanito",
  "email": "juanin@correo.com",
  "password": "password",
  "fidelityPoints": 100
}

### CREAR UN DEVELOPER -- TIENE ROL DEVELOPER
POST http://localhost:8080/api/developer
Content-Type: application/json

{
  "name": "nicolas",
  "password": "password",
  "username": "nico",
  "position": "frontend"
}


### OBTENER UN CLIENTE POR ID
GET http://localhost:8080/api/client/1
Content-Type: application/json  


### ELIMINAR UN CLIENTE
DELETE http://localhost:8080/api/client/1
Content-Type: application/json

### OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/product
Content-Type: application/json


### CREAR UN NUEVO PRODUCTO
POST http://localhost:8080/api/product
Content-Type: application/json  

{
  "name": "producto3",
  "sku": "sku3",
  "price": 990.0,
  "description": "descripcion del producto",
  "stock": 10
}

### CREAR COMPRA (ERROR STOCK INSUFICIENTE)
POST http://localhost:8080/api/carts
Content-Type: application/json 

{
  "clientId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### CREAR COMPRA
POST http://localhost:8080/api/carts
Content-Type: application/json 

{
  "clientId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 3,
      "quantity": 1
    }
  ]
}


### OBTENER TODAS LAS ORDENES
GET http://localhost:8080/api/order
Content-Type: application/json

### OBTENER TODOS LOS CARROS
GET http://localhost:8080/api/carts/1
Content-Type: application/json

### LOGIN - OBTENER TOKEN
POST http://localhost:8080/api/authentication/login
Content-Type: application/json

{
  "username": "nico",
  "password": "password"
}