### OBTENER TODOS LOS USUARIOS
GET http://localhost:8080/api/user
Content-Type: application/json


### CREAR USUARIO -- ROL ADMIN
POST http://localhost:8080/api/authentication/register/admin
Content-Type: application/json

{
  "name": "administrador",
  "username": "admin",
  "password": "password",
  "message": "Soy el mas pulento de todos"

}


### CREAR USUARIO -- ROL CLIENTE
POST http://localhost:8080/api/authentication/register/client
Content-Type: application/json

{
  "name": "juan",
  "username": "juanito",
  "email": "juanin@correo.com",
  "password": "password",
  "fidelityPoints": 100
}

### CREAR USUARIO -- ROL DEVELOPER
POST http://localhost:8080/api/authentication/register/developer
Content-Type: application/json

{
  "name": "nicolas",
  "password": "password",
  "username": "nico",
  "position": "frontend"
}

### LOGIN - OBTENER TOKEN
POST http://localhost:8080/api/authentication/login
Content-Type: application/json

{
  "username": "nico",
  "password": "password"
}

### OBTENER TODOS LOS CLIENTES
GET http://localhost:8080/api/client
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuaWNvIiwiaWF0IjoxNzUyODk5MzE1LCJleHAiOjE3NTI5ODU3MTV9.lOXMav_GTASHOdXMoSIL-AIfptBH7wg9gZrAm2ORORNLkvLOnBlifMxlxHrqJ1nYyll3owSaxRHc8YDmX_f84A

### OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/product
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqdWFuaXRvIiwiaWF0IjoxNzUyODk5MTQyLCJleHAiOjE3NTI5ODU1NDJ9.7LJnhz16TgpFa2zp2OPnH1dRpgf2X7sAjVEHONUCJHX_ZI5HLp-OVWUD1E_eODylsz4-2eszo70vm3wr6dktVA


### OBTENER UN CLIENTE POR ID
GET http://localhost:8080/api/client/1
Content-Type: application/json  


### ELIMINAR UN CLIENTE
DELETE http://localhost:8080/api/client/1
Content-Type: application/json

### OBTENER TODOS LOS PRODUCTOS
GET http://localhost:8080/api/product
Content-Type: application/json


### CREAR UN NUEVO PRODUCTO
POST http://localhost:8080/api/product
Content-Type: application/json  

{
  "name": "producto3",
  "sku": "sku3",
  "price": 990.0,
  "description": "descripcion del producto",
  "stock": 10
}

### CREAR COMPRA (ERROR STOCK INSUFICIENTE)
POST http://localhost:8080/api/carts
Content-Type: application/json 

{
  "clientId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### CREAR COMPRA
POST http://localhost:8080/api/carts
Content-Type: application/json 

{
  "clientId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 3,
      "quantity": 1
    }
  ]
}


### OBTENER TODAS LAS ORDENES
GET http://localhost:8080/api/order
Content-Type: application/json

### OBTENER TODOS LOS CARROS
GET http://localhost:8080/api/carts/1
Content-Type: application/json

